[build]
command = "vite build"
publish = "dist"
base = ""

[build.environment]
NODE_ENV = "production"
VITE_APP_ENV = "production"



[context.production.environment]
VITE_API_URL = "https://api.example.com"

[context.deploy-preview.environment]
VITE_API_URL = "https://staging-api.example.com"

[context.dev.environment]
VITE_API_URL = "http://localhost:3000"

[functions]

    [functions.node_version]
    external_node_modules = [
      "module-one",
      "module-two"
    ]



